# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField(blank=True, max_length=50)),
                ('Name', models.TextField(blank=True, max_length=50)),
                ('Description', models.TextField(blank=True, max_length=50)),
                ('Photos', models.TextField(blank=True, max_length=50)),
                ('Location', models.TextField(blank=True, max_length=50)),
                ('Sex', models.TextField(blank=True, max_length=50)),
                ('SexWant', models.TextField(blank=True, max_length=50)),
                ('RadiusWant', models.IntegerField(blank=True, max_length=50)),
            ],
        ),
    ]
